# Angular velocities (Joints)
max_q1: 0.5 # rad/s
max_q2: 0.5 # rad/s
max_q2: 0.5 # rad/s
max_q4: 0.5 # rad/s
max_q5: 0.5 # rad/s
max_q6: 0.5 # rad/s

# Cartesian linear/angular velocities (Gripper)
max_vx: 1.2 # m/s
max_vy: 0.0 # m/s
max_vz: 0.0 # m/s
max_wx: 0.0 # rad/s
max_wy: 0.0 # rad/s
max_wz: 6.0 # rad/s

# Sign for linear/angular velocities (Gripper)
sign_vx: 1.0
sign_vy: 1.0
sign_vz: 1.0
sign_wx: 1.0
sign_wy: 1.0
sign_wz: 1.0

# Input axes (Joystick)
axis_vx: 1
axis_vy: 0
axis_vz: 3
axis_wx: 0
axis_wy: 1
axis_wz: 2

# Input buttons (Joystick)
up_button: 7
down_button: 9
mode_button: 8
joint_up_button: 4
joint_down_button: 0
deadman_button: 6

# Timeout for joystick reset (<0 no timeout)
joy_msg_timeout: -1
